name: 'kirick13/commit-notify-action'
description: 'Sends notification about commit to Telegram / Discord.'

inputs:
  telegram-bot-token:
    description: 'Telegram: Bot token.'
  telegram-chat-id:
    description: 'Telegram: Chat ID to send message to.'
  discord-bot-token:
    description: 'Discord: Bot token.'
  discord-chat-id:
    description: 'Discord: Chat ID to send message to.'
  repo-description:
    description: 'Description of the repo (Discord only).'
  signature:
    description: 'Signature of the author of the message (Discord only).'

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.21

    - name: Aggregate data
      shell: bash
      run: bun run $GITHUB_ACTION_PATH/aggregate.js
      id: data

    - name: Notify Telegram
      shell: bash
      run: bun run $GITHUB_ACTION_PATH/send-telegram.js
      env:
        DATA: ${{ steps.data.outputs.value }}
        SIGNATURE: ${{ inputs.signature }}
        TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        TELEGRAM_BOT_TOKEN: ${{ inputs.telegram-bot-token }}

    - name: Notify Discord
      shell: bash
      run: bun run $GITHUB_ACTION_PATH/send-discord.js
      env:
        DATA: ${{ steps.data.outputs.value }}
        REPO_DESCRIPTION: ${{ inputs.repo-description }}
        SIGNATURE: ${{ inputs.signature }}
        DISCORD_CHAT_ID: ${{ inputs.discord-chat-id }}
        DISCORD_BOT_TOKEN: ${{ inputs.discord-bot-token }}
