name: 'kirick13/commit-notify-action'
description: 'Sends notification about commit to Telegram / Discord.'

inputs:
  telegram-bot-token:
    description: 'Telegram: Bot token.'
  telegram-chat-id:
    description: 'Telegram: Chat ID to send message to.'
  discord-bot-token:
    description: 'Discord: Bot token.'
  discord-chat-id:
    description: 'Discord: Chat ID to send message to.'
  signature:
    description: 'Signature of the author of the message.'

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.21

    - name: Get changed files
      shell: bash
      run: echo "value=$(git diff --name-status HEAD~1 HEAD | awk '{print $1}')" >> $GITHUB_OUTPUT
      id: files
    - name: Get changed lines
      shell: bash
      run: echo "value=$(git diff --shortstat HEAD~1 HEAD)" >> $GITHUB_OUTPUT
      id: lines

    - name: Set Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Aggregate data
      shell: bash
      run: bun run aggregate.js
      id: data
      env:
        FILES: ${{ steps.files.outputs.value }}
        LINES: ${{ steps.lines.outputs.value }}

    - name: Notify Telegram
      shell: bash
      run: bun run send-telegram.js
      env:
        DATA: ${{ steps.data.outputs.value }}
        TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        TELEGRAM_BOT_TOKEN: ${{ inputs.telegram-bot-token }}

    - name: Notify Discord
      shell: bash
      run: bun run send-discord.js
      env:
        DATA: ${{ steps.data.outputs.value }}
        SIGNATURE: ${{ inputs.signature }}
        DISCORD_CHAT_ID: ${{ inputs.discord-chat-id }}
        DISCORD_BOT_TOKEN: ${{ inputs.discord-bot-token }}
